config/routes.rb
Rails.application.routes.draw do
  resources :beta
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # get '/user/get_demo', to: 'users#get_demo', as: :demo_user
  # get '/user/get_params/:val', to: 'users#get_demo2', as: :get_params

  get '/song/html', to: 'songs#get_three_songs', as: :get_three_songs
  get '/song/json', to: 'songs#get_three_songs_json', as: :get_three_songs_json

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/betum.rb
class Betum < ApplicationRecord
end

app/models/songs.rb
class Songs < ApplicationRecord
  def self.find_c_chord
    where(chord: 'C')
  end
  def self.find_the_beatles
    where(band: 'The beatles')
  end
  def self.find_rock
    where("genre LIKE '%rock%'")
  end
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/beta_controller.rb
class BetaController < ApplicationController
  before_action :set_betum, only: [:show, :edit, :update, :destroy]

  # GET /beta
  # GET /beta.json
  def index
    @beta = Betum.all
  end

  # GET /beta/1
  # GET /beta/1.json
  def show
  end

  # GET /beta/new
  def new
    @betum = Betum.new
  end

  # GET /beta/1/edit
  def edit
  end

  # POST /beta
  # POST /beta.json
  def create
    @betum = Betum.new(betum_params)

    respond_to do |format|
      if @betum.save
        format.html { redirect_to @betum, notice: 'Betum was successfully created.' }
        format.json { render :show, status: :created, location: @betum }
      else
        format.html { render :new }
        format.json { render json: @betum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /beta/1
  # PATCH/PUT /beta/1.json
  def update
    respond_to do |format|
      if @betum.update(betum_params)
        format.html { redirect_to @betum, notice: 'Betum was successfully updated.' }
        format.json { render :show, status: :ok, location: @betum }
      else
        format.html { render :edit }
        format.json { render json: @betum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /beta/1
  # DELETE /beta/1.json
  def destroy
    @betum.destroy
    respond_to do |format|
      format.html { redirect_to beta_url, notice: 'Betum was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_betum
      @betum = Betum.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def betum_params
      params.require(:betum).permit(:name, :phone, :age)
    end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  def get_three_songs
    @songs = Songs.all.limit(3)
  end
  def get_three_songs_json
    songs = Songs.all.limit(3)
    
    render json: songs
  end
  def show
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action:set_user, only:[:show, :edit, :update, :destroy]
  def get_demo
    @val = 'Hello Ruby!'
end
  def get_demo2
    @val = params[:val]
  end
  # GET /users
  # GET /users.json
  def index

    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

respond_to do | format | 
if @user.save
        format.html {redirect_to @user, notice:'User was successfully created.'}
format.json {render:show, status::created, location:@user }
else
        format.html {render:new }
format.json {render json:@user.errors, status::unprocessable_entity }
end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do | format | 
if @user.update(user_params)
format.html {redirect_to @user, notice:'User was successfully updated.'}
format.json {render:show, status::ok, location:@user }
else
        format.html {render:edit }
format.json {render json:@user.errors, status::unprocessable_entity }
end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do | format | 
format.html {redirect_to users_url, notice:'User was successfully destroyed.'}
format.json {head:no_content }
end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.fetch(:user,  {})
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/beta_helper.rb
module BetaHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/beta/_form.html.erb
<%= form_with(model: betum, local: true) do |form| %>
  <% if betum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(betum.errors.count, "error") %> prohibited this betum from being saved:</h2>

      <ul>
      <% betum.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_area :name %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_area :phone %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.datetime_select :age %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/beta/edit.html.erb
<h1>Editing Betum</h1>

<%= render 'form', betum: @betum %>

<%= link_to 'Show', @betum %> |
<%= link_to 'Back', beta_path %>

app/views/beta/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Beta</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th>Age</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @beta.each do |betum| %>
      <tr>
        <td><%= betum.name %></td>
        <td><%= betum.phone %></td>
        <td><%= betum.age %></td>
        <td><%= link_to 'Show', betum %></td>
        <td><%= link_to 'Edit', edit_betum_path(betum) %></td>
        <td><%= link_to 'Destroy', betum, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Betum', new_betum_path %>

app/views/beta/new.html.erb
<h1>New Betum</h1>

<%= render 'form', betum: @betum %>

<%= link_to 'Back', beta_path %>

app/views/beta/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @betum.name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @betum.phone %>
</p>

<p>
  <strong>Age:</strong>
  <%= @betum.age %>
</p>

<%= link_to 'Edit', edit_betum_path(@betum) %> |
<%= link_to 'Back', beta_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Music</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/songs/get_three_songs.html.erb
<h1>Songs</h1>

<table>
  <thead>
    <tr style="font-weight: bold; text-align: center">
      <th>Name</th>
      <th>Brand</th>
      <th>Album</th>
      <th>Genre</th>
      <th>Chord</th>
    </tr>
  </thead>

  <tbody>
    <% @songs.each do |song| %>
      <tr class="check-data">
        <td><%= song.name %><a></a></td>
        <td><%= song.brand %></td>
        <td><%= song.album %></td>
        <td><%= song.genre %></td>
        <td><%= song.chord %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/get_demo.html.erb
<%= @val  %>

app/views/users/get_demo2.html.erb
<%= @val  %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>